// <auto-generated />
using System;
using MagicVilla_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231107163310_DataDefaultEnTablaVillas")]
    partial class DataDefaultEnTablaVillas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_API.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MetrosCuadrados")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "",
                            Detalles = "Detalles de la villa 1",
                            FechaActualizacion = new DateTime(2023, 11, 7, 13, 33, 10, 168, DateTimeKind.Local).AddTicks(9570),
                            FechaCreacion = new DateTime(2023, 11, 7, 13, 33, 10, 168, DateTimeKind.Local).AddTicks(9559),
                            ImagenUrl = "",
                            MetrosCuadrados = 150.5,
                            Nombre = "Villa 1",
                            Ocupantes = 5,
                            Tarifa = 1500.5
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "",
                            Detalles = "Detalles de la villa 2",
                            FechaActualizacion = new DateTime(2023, 11, 7, 13, 33, 10, 168, DateTimeKind.Local).AddTicks(9574),
                            FechaCreacion = new DateTime(2023, 11, 7, 13, 33, 10, 168, DateTimeKind.Local).AddTicks(9573),
                            ImagenUrl = "",
                            MetrosCuadrados = 1540.5,
                            Nombre = "Villa 2",
                            Ocupantes = 15,
                            Tarifa = 10500.5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
